feat: project search view
wafflestudio/guam-community-mobile pull request #163
Opened 2022-11-08 11:51 UTC by kwish2

프로젝트 검색 뷰(+필터링) 부분 만들었습니다

2022-11-10 15:55 UTC, YeonghyeonKO requested changes
크게 수정할 부분은 없고, '검색' 버튼에 대한 매우 간단한 기능 수정만 하면 될 것 같습니다!!

2022-11-10 15:55 UTC, YeonghyeonKO commented on lib/screens/recruit/search/project_search.dart
> +            removeDue: ()=>setState((){filter.remove('due');}),
별건 아닌데 single line이라 => 문법이 더 깔끔할 것 같습니다

```suggestion
            removeSkill: ()=>setState(() => filter.remove('skill')),
            removePosition: ()=>setState(() => filter.remove('position')),
            removeDue: ()=>setState(() => filter.remove('due')),
```

2022-11-10 15:55 UTC, YeonghyeonKO commented on lib/screens/recruit/search/filter_status.dart
> +  };
예전 괌에서는 서버에서 techStack 호출 API까 따로 있었는데, 변경 가능성이 거의 없는 constant를 대상으로 호출하려니 괜히 돌아가는 짓인가? 싶더라구요. 클라단에 다 저장하는건 어떻게 보시나요? (S3에 icon 이미지는 넣어두고 path도 클라에서 저장하는 걸루..)

2022-11-10 15:55 UTC, YeonghyeonKO commented on lib/screens/recruit/search/project_search.dart
> +          });
아래처럼 setSkill, setPosition, setDue의 값(함수 type)을 모듈화하여 사용도 가능할 것 같습니다! 
(e는 toString 필요 없어도 될 것 같은데 확인해봐야겠네요)
```
_setFilter(e) {
  setState(() {
    String eString = e.toString;
    if (e == null) {
      filter.remove(eString);
    } else {
      filter[eString] = e;
    }
  });
}
```

```suggestion
        trailing: FilterButton(filter: filter, setSkill: (skill) => _setFilter(skill),
```

2022-11-10 15:55 UTC, YeonghyeonKO commented on lib/screens/recruit/search/project_search_text_field.dart
> +                  controller.clear();
소원님 'x' 키는 검색어만 clear 하는 것이라 잘 동작하는데, '취소' 키는 아무래도 검색 자체를 취소한다는 의미로 받아들여져서 뒤로 보내는게 맞을 것 같아요. (왜냐하면 프로젝트 탭으로 돌아가려면 Bottom Navigation 터치를 할 수밖에 없다는게 부자연스러운 것 같아서요!)

2022-11-17 03:34 UTC, kwish2 commented on lib/screens/recruit/search/filter_status.dart
> +  };
네 클라에 저장하는 게 좋을 것 같아요.

2022-11-17 03:37 UTC, kwish2 commented on lib/screens/recruit/search/project_search_text_field.dart
> +                  controller.clear();
넵 수정해보겠습니다

2022-11-17 06:26 UTC, YeonghyeonKO commented on lib/screens/recruit/search/filter_status.dart
> +  };
넵 좋습니다!

2022-11-17 14:02 UTC, kwish2 commented on lib/screens/recruit/search/project_search_text_field.dart
> +                  controller.clear();
그러면 취소버튼은 항상 보이는게 나을까요?

2022-11-18 07:09 UTC, YeonghyeonKO approved these changes
LGTM

2022-11-18 07:09 UTC, YeonghyeonKO commented on lib/screens/recruit/search/project_search_text_field.dart
> +                }
@kwish2 소원님 혹시 '취소' 누르고 다시 들어갔을 때 일부러 기존 검색어를 textField에 남기신게 아니라면 아래처럼 clear하면 좋을 것 같습니다! 이거 확인하는 것 빼곤 approve입니당!

```suggestion
                onPressed: () {
                  controller.clear();
                  isTextEmpty = true;
                  Navigator.pop(context);
                }
```

2022-11-18 11:33 UTC, merged