Feature/mention
wafflestudio/guam-community-mobile pull request #54
Opened 2022-02-21 15:06 UTC by YeonghyeonKO

> resolves #42 

- [ ] '@' 입력 시 글/댓글 작성자 프로필 사진 및 닉네임을 입력창 상단에 표출하기

- [ ] 멘션된 프로필 닉네임 색 다르게 처리하기

- [ ] 멘션된 프로필 id를 리스트 형태로 저장하기

2022-02-22 02:18 UTC, gajagajago commented
오늘 중 리뷰하겠습니다.

2022-02-22 12:20 UTC, gajagajago requested changes
몇 가지 커멘트 남겼습니다. 확인 부탁드려요~! Re request 부탁드립니다.

2022-02-22 12:20 UTC, gajagajago commented on lib/screens/boards/posts/detail/post_detail.dart
> +                mentionList: mentionList,
mentionList를 만들어서 넘겨줘야 하는 이유가 뭔가요? 일반적으로는 debounce가 걸린 query를 해서 서버에서 mentionable 한 list를 받는데, 이렇게 static하게 리스트를 넘겨주도록 한 이유가 있나요?

2022-02-22 12:20 UTC, gajagajago commented on lib/screens/boards/posts/detail/post_detail.dart
> +        continue;
set은 중복을 허용하지 않는 자료구조인데, item type이 Map일 땐 중복 체크가 안되나요? 또한 imperative 말고 declarative한 코드면 더 가독성이 높을 것 같습니다.

2022-02-22 12:20 UTC, gajagajago commented on lib/models/profiles/profile.dart
> +@JsonSerializable(explicitToJson: true) // nested Instance -> json
이거 필요한 코드인가요? 어떤 의미인가요?

2022-02-22 12:20 UTC, gajagajago commented on lib/models/picture.dart
> +  Map<String, dynamic> toJson() => {'id': id, 'urlPath': urlPath};
Picture toJson 은 어디에서 필요한가요?

2022-02-22 12:22 UTC, gajagajago commented on lib/screens/boards/posts/detail/post_detail.dart
> +                mentionList: mentionList,
만약 테스트를 위한 거라면, 그냥 삭제하고 // TODO: fetch mentionable nickname list from server 같은 거를 common text field에 남겨놓는 게 나을 것 같습니다.

2022-02-22 14:11 UTC, YeonghyeonKO commented on lib/main.dart
> +            child: Portal(
네 Portal은 MaterialApp 위에서 동작하는데, 현재 개발된 위젯 가운데 MaterialApp을 사용하는 컴포넌트가 최상단 뿐이라 넣었습니다. flutter_mention 개발자가 Portal을 필수적으로 사용하도록 만들었는데, Portal의 maintainer가 없는 상황이니 아예 멘션을 사용하지 말아버릴까요..

2022-02-22 14:23 UTC, YeonghyeonKO commented on lib/models/profiles/profile.dart
> +@JsonSerializable(explicitToJson: true) // nested Instance -> json
해당 애노테이션을 통해서 `{name: John, address: Instance of 'address'}` 와 같은 형태에서 instance까지도 json 형태로 풀어줄 수 있는데, photo를 instance가 아니라 urlPath로만 정의해서 이제는 필요없는 애노테이션이 되어버렸네요. 삭제하겠습니다!

2022-02-22 14:24 UTC, YeonghyeonKO commented on lib/models/picture.dart
> +  Map<String, dynamic> toJson() => {'id': id, 'urlPath': urlPath};
이 부분 서버 response 바뀌면서 이제 안쓰니 삭제하겠습니다!

2022-02-22 14:24 UTC, YeonghyeonKO commented on lib/screens/boards/posts/detail/post_detail.dart
> +                mentionList: mentionList,
@gajagajago 멘션 기획 시에 서버로부터 list를 받지 않고 클라에서 들고 있는 프로필들로 넘겨주기로 했었습니다!

2022-02-22 14:33 UTC, gajagajago commented on lib/screens/boards/posts/detail/post_detail.dart
> +                mentionList: mentionList,
아 그렇군요. 클라에서 들고 있는 프로필이란 결국 comment 스레드에 있는 애들인 거죠?

2022-02-22 14:36 UTC, gajagajago commented on lib/main.dart
> +            child: Portal(
음 제가 봤을 땐 꼭 MaterialApp 위에 위치하지 않아도 되는 것 같습니다. 일반 위젯 위에 놓아도 적용되는 것 같습니다. 
일단 개발 끝났으니 넣어놓고, 대신 해당 레포 watch 걸어놓고 변동 사항 생기면 대응하면 될 것 같습니다. 만약 wind down 하는 거 같으면 서브 모듈로 빼서 커스텀해서 쓰면 될 것 같습니다.

2022-02-23 01:33 UTC, YeonghyeonKO commented on lib/screens/boards/posts/detail/post_detail.dart
> +                mentionList: mentionList,
넵 다만 post-preview에서 오는 게시글 작성자 프로필 1개와 post-detail에서 새롭게 서버와 통신하는 댓글 response에서 뽑아낼 프로필 n개가 합쳐지게 됩니다!

2022-02-23 01:40 UTC, YeonghyeonKO commented on lib/main.dart
> +            child: Portal(
넵! 제가 사실 플러그인으로 하기 전에 Portal만 설치하고 flutter_mentions은 다 복붙해서 써봤는데 에러가 뜨더라구요 ㅋㅋㅋㅋ 당시 잘못 붙였으리라 생각합니다.

2022-02-26 01:30 UTC, gajagajago approved these changes

2022-02-26 03:33 UTC, merged